### PR TITLE
Do not rely on "Content-Length" for payload size.

### LINKED ISSUE #209: Payload size isn't correct for some transactions
## :loudspeaker: Describe the bug
Some transactions show payload size as `-1`. It is totally fine, since OkHttp returns this value in case the size is unknown. However, when I wanted to handle this value in Chucker UI I decided to check what other network interceptors show and found out that [Stetho](https://facebook.github.io/stetho/) show sizes for transactions, which show `-1` in Chucker.

### :wrench: Expected behavior
Transactions show actual size instead of `-1`.

## :camera: Screenshots
Screen Shot 2020-01-26 at 10 51 39

### PR DESCRIPTION
**Pull request by MiSikora**
## :camera: Screenshots

| Before | After |
| --- | --- |
| Screenshot_20200719-064434 | Screenshot_20200719-064034 |

## :page_facing_up: Context

There is an open issue - #209. Also, recently the community asked for it.

## :pencil: Changes

Two main changes. I redesigned a little bit DB entities to reflect that they have payload size and not content length. This required a destructive migration. Since this is changed, the field is set after the response read is done by `ChuckerInterceptor` and it does not rely on the `Content-Length` header.

## :no_entry_sign: Breaking

No.

## :hammer_and_wrench: How to test

Run the sample app. Responses without the `Content-Length` headers should display now payload size correctly. Also, some tests were written.

## :stopwatch: Next steps

Closes #209.

### CODE REVIEW

File: library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt [hunk 1]
```diff
@@ -90,10 +90,11 @@ internal class TeeSource(
...
         /**
          * Called when the upstream was closed. All read bytes are copied to the [file].
-         * This does not mean that the content of a [file] is valid. Only that the user
-         * is done with the reading process.
+         * This does not mean that the content of the [file] is valid. Only that the user
+         * is done with the reading process. [totalBytesRead] is the exact amount of data
+         * that the client downloaded even if the [file] is corrupted.
          */
-        fun onClosed(file: File)
+        fun onClosed(file: File, totalBytesRead: Long)
```
Comment (cortinico) [inline library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt:97]: Let's invert the parameter order either here or in the onFailure:

```kotlin
fun onClosed(file: File, totalBytesRead: Long)
fun onFailure(file: File, exception: IOException)
```

File should always be either the first or the last param.

File: library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt [hunk 2]
```diff
@@ -198,4 +198,86 @@ class ChuckerInterceptorTest {
...
+        source.use { it.readByteString(segmentSize.toLong()) }
+
+        val transaction = chuckerInterceptor.expectTransaction()
+        assertThat(transaction.responseHeaders).contains(
+            """
+            |  {
+            |    "name": "Content-Length",
+            |    "value": "${body.size()}"
+            |  }
+            """.trimMargin()
```
Comment (cortinico) [inline library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt:246]: You should be able to remove the `|` and change this to `.trimIndent()`

Comment (MiSikora) [reply library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt:246]: It won't work, unfortunately. JSON has this structure.

```json
[
  {
    "name": "Content-Length",
    "value": "x"
  }
]
```

`.trimIndent()` would remove first indentation before `{` and `}`. And I didn't want to compare the whole content as it would make assumptions on no other headers being there.

File: library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt [hunk 3]
```diff
@@ -83,22 +83,23 @@ internal class TeeSource(
...
+            callback.onFailure(sideChannel, exception)
         }
     }
 
     interface Callback {
         /**
          * Called when the upstream was closed. All read bytes are copied to the [file].
-         * This does not mean that the content of a [file] is valid. Only that the user
-         * is done with the reading process.
+         * This does not mean that the content of the [file] is valid. Only that the user
```
Comment (vbuberen) [inline library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt:93]: Minor observation - I guess `user` on this line and `client` on 95 mean the same thing. Suggest to pick one word for naming. `client` seems more suitable for this case.

File: library/src/test/java/com/chuckerteam/chucker/ChuckerInterceptorDelegate.kt [hunk 4]
```diff
@@ -12,10 +12,10 @@ import okhttp3.Response
 import java.util.concurrent.CopyOnWriteArrayList
 import java.util.concurrent.atomic.AtomicLong
 
-internal class ChuckerInterceptorDelegate(
-    fileFactory: FileFactory,
-    maxContentLength: Long = 250000L,
-    headersToRedact: Set<String> = emptySet()
+internal data class ChuckerInterceptorDelegate(
```
Comment (vbuberen) [inline library/src/test/java/com/chuckerteam/chucker/ChuckerInterceptorDelegate.kt:15]: Not sure I understood what this change gives us. Could explain, please?

Comment (MiSikora) [reply library/src/test/java/com/chuckerteam/chucker/ChuckerInterceptorDelegate.kt:15]: It comes from this test.

https://github.com/ChuckerTeam/chucker/blob/e3e259a46d057d06ca33387236a93e0ae7221d25/library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt#L269-L282

Since the interceptor is created in `setUp` there is no way of changing its input parameters. I wanted to have more granular control over that and an explicit test.

Comment (MiSikora) [reply library/src/test/java/com/chuckerteam/chucker/ChuckerInterceptorDelegate.kt:15]: Now that I'm thinking `copy` is not needed. I could just create a new interceptor. What do you think?

Comment (vbuberen) [reply library/src/test/java/com/chuckerteam/chucker/ChuckerInterceptorDelegate.kt:15]: It might be a question of preference. I think creation of a new interceptor would be sort of more understandable for a new reader of the code.
