### PR TITLE
File creation fix

### LINKED ISSUE #414: Potential NPE during AndroidCacheFileFactory initialization
## :writing_hand: Describe the bug
The current code at: https://github.com/ChuckerTeam/chucker/blob/develop/library/src/main/java/com/chuckerteam/chucker/internal/support/AndroidCacheFileFactory.kt#L17 assumes that `context.cacheDir` returns non-null value. However, on Android older than 7.0 this method can return `null`: http://androidxref.com/6.0.0_r1/xref/frameworks/base/core/java/android/app/ContextImpl.java#425

## :bomb: Steps to reproduce
1. Cause cache dir to be not creatable eg. create regular file with the same name beforehand or fill entire disk space.
2. Invoke `ChuckerInterceptor` constructor.

## :wrench: Expected behavior
Not sure what is that cache used for. If it is mandatory, NPE could be wrapped by IOException.

## :camera: Screenshots
N/A

## :iphone: Tech info
 - OS: < 7.0
 - Chucker version: at least one which is built from commit https://github.com/ChuckerTeam/chucker/commit/392a63b8043f3c967558a49bf84db481870537a2 or newer.

## :page_facing_up: Additional context
I haven't encountered this issue at runtime. Just realized that it may happen during https://github.com/ChuckerTeam/chucker/issues/413 investigation.

### LINKED ISSUE #422: IOException when app uses 3rd party SDK
## :writing_hand: Describe the bug
This issue arises from #394 

After fixes for #394 the reporter [provided update](https://github.com/ChuckerTeam/chucker/issues/394#issuecomment-671868443) that another exception appeared:

> ```
>  java.io.IOException: No such file or directory
>         at java.io.UnixFileSystem.createFileExclusively0(Native Method)
>         at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
>         at java.io.File.createNewFile(File.java:1008)
>         at com.chuckerteam.chucker.internal.support.AndroidCacheFileFactory.create(AndroidCacheFileFactory.kt:21)
>         at com.chuckerteam.chucker.internal.support.AndroidCacheFileFactory.create(AndroidCacheFileFactory.kt:15)
>         at com.chuckerteam.chucker.api.ChuckerInterceptor.multiCastResponseBody(ChuckerInterceptor.kt:184)
>         at com.chuckerteam.chucker.api.ChuckerInterceptor.intercept(ChuckerInterceptor.kt:92)
> ```
> It happens even after removing the application from device and reinstalling a new one.

## :wrench: Expected behavior
Chucker works normally and shows transactions.

## :iphone: Tech info
 - Chucker version: 3.3.0-SNAPSHOT (as of 11th of August 2020)

## :page_facing_up: Additional context
We should investigate the issue to either fix it or to get all the info we might need to deal with possible problems with other 3rd party SDKs.

### PR DESCRIPTION
**Pull request by MiSikora**
## :page_facing_up: Context

There are open issues - #422, #414.

## :pencil: Changes

`FileFactory` is now IO safe and typesafe. I removed the interface in favor of a concrete implementation. It was internal anyway and it was misleading in tests of `ChuckerInterceptor` because fake implementation did not take into account stuff like `createNewFile()`, that was the cause of #422. 

One more thing that I changed in the implementation of the factory is that access to the parent directory. It is now lazy, so it should help with #413 since the cache directory will no longer be accessed during initialization. It won't fix it as there are other files being used on the main thread but it is one step forward.

~~I'm not particularly happy about the fact that `TeeSource` accepts now `File?` as an input parameter but I didn't want to overcomplicate things by introducing another source that just counts bytes downloaded.~~ - This isn't the case anymore. See https://github.com/ChuckerTeam/chucker/pull/427#issuecomment-677716291.

## :paperclip: Related PR

I copied the test for the file factory from #423.

## :no_entry_sign: Breaking

No.

## :hammer_and_wrench: How to test

In practice not sure. Maybe @CodeBreak524 can test with a dependency from my branch on JitPack (`com.github.MiSikora.chucker:library:file-creation-fix-SNAPSHOT`). I didn't write new tests for `ChuckerInterceptor` as old ones cover this case due to using real file factory in tests.

## :stopwatch: Next steps

Closes #422
Closes #414
Closes #423

### CODE REVIEW

File: library/src/main/java/com/chuckerteam/chucker/internal/support/FileFactory.kt [hunk 1]
```diff
@@ -1,8 +1,29 @@
...
+
+    fun create(filename: String): File? = try {
+        val directory = getFileDirectory()
+            ?: throw FileNotFoundException("Failed to create directory for temporary Chucker files")
+        File(directory, filename).apply {
+            if (exists()) {
+                delete()
+            }
+            parentFile?.mkdirs()
+            createNewFile()
```
Comment (koral--) [inline library/src/main/java/com/chuckerteam/chucker/internal/support/FileFactory.kt:23]: Shouldn't we fail fast here if this invocation returned `false`?

Comment (MiSikora) [reply library/src/main/java/com/chuckerteam/chucker/internal/support/FileFactory.kt:23]: I'm not sure. `createNewFile()` returns `false` only if the file already exists according to documentation. In that case, it might be more accurate to do something like this.

```kotlin
if (exists() && !delete()) {
  throw IOException("Failed to delete temporary Chucker file $file")
}
```

File: library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt [hunk 2]
```diff
@@ -234,28 +233,26 @@ class ChuckerInterceptor internal constructor(
...
     ) : TeeSource.Callback {
 
-        override fun onClosed(file: File, totalBytesRead: Long) {
-            val buffer = try {
-                readResponseBuffer(file, response.isGzipped)
-            } catch (e: IOException) {
-                null
-            }
+        override fun onClosed(file: File?, totalBytesRead: Long) {
+            val buffer = file?.let { readResponseBuffer(it, response.isGzipped) }
```
Comment (vbuberen) [inline library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt:237]: I would suggest to avoid `?.let { }` here and use just `if (file != null) {...` to not introduce additional useless variable multiple times (as this fun will be called for each transaction).
Suggestion is based on [this article](https://medium.com/mobile-app-development-publication/kotlin-dont-just-use-let-7e91f544e27f) and recommendation 1.1 from the mentioned article.

File: library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt [hunk 3]
```diff
@@ -18,12 +18,12 @@ import java.io.IOException
...
 internal class TeeSource(
     private val upstream: Source,
-    private val sideChannel: File,
+    private val sideChannel: File?,
     private val callback: Callback,
     private val readBytesLimit: Long = Long.MAX_VALUE
 ) : Source {
     private val sideStream = try {
-        Okio.buffer(Okio.sink(sideChannel))
+        sideChannel?.let { Okio.buffer(Okio.sink(it)) }
```
Comment (vbuberen) [inline library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt:26]: Same suggestion about using `if (sideChannel != null)` as in the previous comment.

**Review by vbuberen — COMMENTED** [review]
Thanks for such a good change. Looks good to me. 
Only a few minor comments with suggestions for micro-optimizations.

Also, I see a typo in PR description with wrong PR mentioned in the first part in `that was the cause of #420.` Please update it as well to have proper history descriptions.

**Comment by MiSikora** [comment]
Ok, I applied your suggestions. I would appreciate it if you can give feedback on https://github.com/ChuckerTeam/chucker/pull/427#discussion_r471637023 from @koral-- and how you'd like to handle it.

**Comment by MiSikora** [comment]
Coverted it to a draft because I discovered some issues.

**Comment by MiSikora** [comment]
In 130d59d I decoupled tee operation from reporting functionality. Reporting is now a part of a `ReportingSink` class. My main motivation was that `TeeSource` started to become too complex and was had too many responsibilities.

**Comment by cortinico** [comment]
> CI fails for now because I added a functional interface and #438 needs to be merged first. I'll rebase after. Unless you think that `() -> File?` and a type alias will suffice.

Since we're on 1.4, let's go with a functional interface 👌

**Review by cortinico — APPROVED** [review]
Left some nits. Overall the change looks good to me. 

Thank you very much for taking the time to do this change @MiSikora 🙏 
I'd love to get a pass also from @vbuberen if possible before merging 👌

File: library/src/main/java/com/chuckerteam/chucker/internal/support/CacheDirectoryFactory.kt [hunk 4]
```diff
@@ -0,0 +1,7 @@
+package com.chuckerteam.chucker.internal.support
+
+import java.io.File
+
+internal fun interface CacheDirectoryFactory {
+    fun create(): File?
```
[the remark this answers is not in the document]
Comment (MiSikora) [reply library/src/main/java/com/chuckerteam/chucker/internal/support/CacheDirectoryFactory.kt]: 👍  I even named it `Provider` in the first implementation, but didn't want to add a mental overhead of differentiation between factories and providers.

**Comment by MiSikora** [comment]
Great, thanks! I added also one test for a missing cache in the first place.

**Review by vbuberen — APPROVED** [review]
LGTM!
