### PR TITLE
Fetch payload in AsyncTask

### LINKED ISSUE #55: Chucker is crashing opening responses with big bodies
**Describe the bug**

I do have an app that is calling an endpoint that returns a JSON Body of nearly 700kb.
Chucker is blocking the UI thread trying to parse the body and is causing an ANR/Crash if trying to inspect the response body.

**To Reproduce**
1. Use Chucker to call an endpoint with a big response
2. Click on the Chucker Push notification
3. Open the HTTP Request from the list
4. Click on the "Response" tab

**Expected behavior**
The tab should open immediately

**Actual behavior**
The Chucker UI is completely frozen and eventually crashes

**Smartphone**
 - Emulator - Nexus 5X
 - OS: API27
 - Lib version: 3.0.0-alpha1

### PR DESCRIPTION
**Pull request by redwarp**
To avoid the formating of json or xml stalling the UI, the payload will be loaded and formatted in an async task instead.
Fixes #55

### CODE REVIEW

File: library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt [hunk 1]
```diff
@@ -121,6 +117,31 @@ internal class TransactionPayloadFragment : Fragment(), TransactionFragment, Sea
...
+                )
+                else -> Triple(
+                    transaction.getResponseHeadersString(true),
+                    transaction.getFormattedResponseBody(),
+                    transaction.isResponseBodyPlainText
+                )
+            }
+        }
+
+        override fun onPostExecute(result: Triple<String, String, Boolean>) {
```
Comment (cortinico) [inline library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt]: How about having a progress bar and hiding it in the `onPreExecute`?

**Comment by cortinico** [comment]
You can use this Charles rewrite rule:
[BigGetResponse.xml.zip](https://github.com/ChuckerTeam/chucker/files/3473049/BigGetResponse.xml.zip)

Plus you need to remove SSL to let it work properly here:
https://github.com/ChuckerTeam/chucker/blob/1e893c2a6bfa16e3d41bd9488f84a698d060e13e/sample/src/main/java/com/chuckerteam/chucker/sample/SampleApiService.java#L35-L36

**Comment by redwarp** [comment]
Verified with a big query that it actually solves the issue.

File: library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt (hunk 1 above)
Comment (redwarp) [reply library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt]: I rebased. I think a progress bar could be nice, but can be done separately.

File: library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt [hunk 2]
```diff
@@ -129,19 +129,45 @@ internal class TransactionPayloadFragment : Fragment(), TransactionFragment, Sea
...
+
+            val bitmap = transaction.responseImageData?.let { imageData ->
+                BitmapFactory.decodeByteArray(imageData, 0, imageData.size)
+            }
+
+            return when (type) {
+                TYPE_REQUEST -> UiPayload(
+                    transaction.getRequestHeadersString(true),
+                    transaction.getFormattedRequestBody(),
+                    transaction.isRequestBodyPlainText, bitmap
```
Comment (cortinico) [inline library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt]: Can you put it on 2 lines?
```suggestion
                    transaction.isRequestBodyPlainText, 
                    bitmap
```

File: library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt [hunk 3]
```diff
@@ -129,19 +129,45 @@ internal class TransactionPayloadFragment : Fragment(), TransactionFragment, Sea
...
+                )
+                else -> UiPayload(
+                    transaction.getResponseHeadersString(true),
+                    transaction.getFormattedResponseBody(),
+                    transaction.isResponseBodyPlainText, bitmap
```
Comment (cortinico) [inline library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt]: Can you put it on 2 lines?
```suggestion
                    transaction.isResponseBodyPlainText, 
                    bitmap
```

File: library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt (hunk 2 above)
Comment (redwarp) [reply library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt]: Damn. Sorry, our work project's setup make that happen automatically when formatting, I though the same would happen here :-P
