### PR TITLE
Fix for not closed GzipSource

### LINKED ISSUE #472: StrictModeViolation: GzipSource is not closed
## :writing_hand: Describe the bug
```
Caused by: java.lang.Throwable: Explicit termination method 'end' not called
   at dalvik.system.CloseGuard.open(CloseGuard.java:237)
   at java.util.zip.Inflater.<init>(Inflater.java:122)
   at okio.GzipSource.<init>(GzipSource.kt:44)
   at com.chuckerteam.chucker.internal.support.IOUtils.getNativeSource(IOUtils.kt:59)
   at com.chuckerteam.chucker.api.ChuckerInterceptor.processRequest(ChuckerInterceptor.kt:132)
   at com.chuckerteam.chucker.api.ChuckerInterceptor.intercept(ChuckerInterceptor.kt:97)
```

## :bomb: Steps to reproduce
```
StrictMode.setVmPolicy(
  VmPolicy.Builder()
    .detectLeakedClosableObjects()
    .penaltyLog()
    .penaltyDeath()
)
```

Call an endpoint using gzip compression.

## :wrench: Expected behavior
No violation. `GzipSource` is closed.

## :iphone: Tech info
 - Chucker version: 3.3.0

### PR DESCRIPTION
**Pull request by vbuberen**
## :page_facing_up: Context
There is an issue #472 
Issue appears with StrictMode enabled. We couldn't catch the issue earlier, because sample app has no gzip request with body, so code with error wasn't reachable.

## :pencil: Changes
- Fixed the issue by adding `use { }` function to GzipSource in `getNativeSource()` function.
- Updated tests to use real `Buffer()`, since Mockk can't properly react to `close()` call.
- Added a fake Gzip request which I fill with some dummy request body and header telling that response is with gzip encoding. It returns 405, but allows to reproduce the issue.
- Added StrictMode to the sample app, because this is not the first time we have issues reported by people with this mode enabled (for example #421)
- (UPD: after review) Renamed existing gzip request to explicitly mention that it returns just gzip response.

## :hammer_and_wrench: How to test
To reproduce the issue remove `use` from `getNativeSource()` and use just GzipSource directly. With StrictMode enabled sample will crash when `fakeGzipRequest()` is called.

## :stopwatch: Next steps
We might want to improve the part of request processing and cover it with some more tests.
Closes #472

### CODE REVIEW

File: sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt [hunk 1]
```diff
@@ -127,6 +128,24 @@ class HttpBinClient(
         )
     }
 
+    private fun fakeGzipRequest() {
```
Comment (MiSikora) [inline sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt:131]: We can avoid custom function with a header on a Retrofit function. We could also use `/post` instead of `/gizp` to get back the result instead of `405`.

```kotlin
@POST("/post")
@Headers("Content-Encoding: gzip")
fun postGzipped(@Body body: Data): Call<Any?>
```

**Review by MiSikora — COMMENTED** [review]
Left one minor thing.

As far as the requests revamp go I think we should go with a similar route to responses processing.

File: sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt (hunk 1 above)
Comment (vbuberen) [reply sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt:131]: Yeah, this one looks nicer. Added `/gzip` just to have a visual clue on what request it is.

**Review by MiSikora — APPROVED** [review]
