### PR TITLE
Limit size of binary image to 1 million bytes.

### LINKED ISSUE #94: Image that are too big will make chucker crash
**Describe the bug**
Because the image data is stored in database, if an image is too big, it crashes

**To Reproduce**
1. Use Chucker to download a really big image, like https://i.ibb.co/znbM2dp/IMG-20190812-194359.jpg

**Expected behavior**
Chucker should work

### PR DESCRIPTION
**Pull request by redwarp**
It prevents the SQLiteBlobTooBigException that would happen when downloading big images.

Fixes #94

### CODE REVIEW

File: library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt [hunk 1]
```diff
@@ -126,7 +126,7 @@ class ChuckerInterceptor @JvmOverloads constructor(
             } else {
                 transaction.isResponseBodyPlainText = false
 
-                if (transaction.responseContentType?.contains("image") == true) {
+                if (transaction.responseContentType?.contains("image") == true && buffer.size() < 1000_000L) {
```
Comment (cortinico) [inline library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt]: Can we export `1000_000L` to a constant?

**Comment by redwarp** [comment]
Extracted 1000_000L to a constant.
