### PR TITLE
Multi cast upstream response for Chucker consumption.

### LINKED ISSUE #218: OutOfMemoryError in interceptor
## :loudspeaker: Describe the bug
This came to me from firebase crashlytics, i don't know the reproduction steps
```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 13536178 byte allocation with 5074056 free bytes and 4MB until OOM
       at okio.Buffer.readByteArray(Buffer.java:1438)
       at okio.Buffer.readString(Buffer.java:301)
       at okio.Buffer.readString(Buffer.java:290)
       at com.chuckerteam.chucker.api.ChuckerInterceptor.processResponseBody(ChuckerInterceptor.java:156)
       at com.chuckerteam.chucker.api.ChuckerInterceptor.processResponse(ChuckerInterceptor.java:130)
       at com.chuckerteam.chucker.api.ChuckerInterceptor.intercept(ChuckerInterceptor.java:61)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:87)
// rest of interceptors
```

## :bomb: To Reproduce
I don't know how to reproduce that

### :wrench: Expected behavior
Chucker should handle any payload size gracefully

## :iphone: Smartphone
 - Device: Galaxy A5 (2016)
 - OS: 7.1.1
 - Lib version: 3.1.1

### LINKED ISSUE #263: ChuckerInterceptor fetches the whole body even if the application isn't doing so
Simply plugging in `ChuckerInterceptor` causes the whole response body to be read, even if the application isn't reading the whole of it. Not only this is a very unwanted side effect, this can also crash the app. This is an example crash while trying to (not) read a ~50MB file:

    2020-03-04 22:49:34.915 8061-8119 E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
        Process: process, PID: 8061
        java.lang.OutOfMemoryError: Failed to allocate a 102720552 byte allocation with 25165824 free bytes and 31MB until OOM, target footprint 260095632, growth limit 268435456
            at java.lang.StringFactory.newStringFromBytes(StringFactory.java:225)
            at java.lang.StringFactory.newStringFromBytes(StringFactory.java:249)
            at okio.Buffer.readString(Buffer.kt:306)
            at okio.Buffer.readString(Buffer.kt:295)
            at com.chuckerteam.chucker.api.ChuckerInterceptor.processResponseBody(ChuckerInterceptor.kt:159)
            at com.chuckerteam.chucker.api.ChuckerInterceptor.processResponse(ChuckerInterceptor.kt:133)
            at com.chuckerteam.chucker.api.ChuckerInterceptor.intercept(ChuckerInterceptor.kt:65)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
            at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
            at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
            at java.lang.Thread.run(Thread.java:919)

you can reproduce this by starting a fake web server and looking at how much it sends (and observing the crash):

    cat /dev/urandom > file
    { echo -ne "HTTP/1.0 200 OK\r\nContent-Length: $(wc -c <file)\r\n\r\n"; cat file } | pv | nc -l 8080

It is my impression that the interceptor should only observe the doings of the application and should report either what the application reads or what the device receives.

P.S. setting `maxContentLength` in `ChuckerInterceptor()` seems to have no effect

### PR DESCRIPTION
**Pull request by MiSikora**
##  :page_facing_up: Context

There are couple of issues. #218 #263 

## :pencil: Changes

I changed mostly `ChuckerInterceptor`. It uses now custom source for responses that multicasts to end consumer and to a temporary file from which Chucker can read once the consumption is done by the end consumer.

## :paperclip: Related PR

There will be conflicts with #250. I would suggest to merge this one first. It will be easier to account for changes in #250 than other way around.

## :no_entry_sign: Breaking

No. I changed the constructor but I made it internal and added another one that is public and compatible with the old one.

## :hammer_and_wrench: How to test

I don't know how to manually test it reliably. Make a request for a really big file and save it on a device you should get an OOM with the old code.

Theoretically user still can get errors if there is not enough disk space but I see it as an edge case with limiting the response size.

## :stopwatch: Next steps

No further steps expected. Maybe we should create an issue for doing the same with requests? Also, maybe Chucker should process these files on its custom `Executor`.

Closes #218
Closes #263

### CODE REVIEW

**Comment by MiSikora** [comment]
Hmmm… I see now that for some reason `deflate` request is not getting processed. Will dig into it.

**Comment by MiSikora** [comment]
I know that testing is lacking but for the things that I fixed in 4751cf0 and 03990f6 but it would be much easier for me to write tests for it in #250 after this one is merged. Would it be ok with you guys?

**Comment by vbuberen** [comment]
Hey @MiSikora. Yeah, probably, it would be easier.
The only moment here is that I am not a big fan of this approach with having some temp files. I would like to stick to approach with in-memory handling of the request/response, since storage is slower than RAM and because I would prefer Chucker to leave as low footprint on the device/emulator as possible.

Another moment that disturbs me that currently all the changes in the core of the library (classes like ChuckerInterceptor) are done mainly without any distinct vision or plan, so each individual pushes his own. I am against it, because it makes project development unpredictable and the library itself being a box of different approaches instead of following some defined vision.

**Comment by MiSikora** [comment]
Hi @vbuberen. This is a proposal implementation of a thing discussed here. https://github.com/ChuckerTeam/chucker/issues/242#issuecomment-591329250

**Comment by MiSikora** [comment]
@vbuberen @cortinico Any further thoughts on this? I'll gladly discuss my reasoning behind this implementation.

File processing seems better to me because it has lower impact on a device. If responses were multicasted to a in-memory buffers, then it might still result in OOM for multiple request. This is not very likely, but plausible. What is more realistic scenario is increased request size to some amount that would not fit in the memory. This would result in the OOM for sure. With multiple parallel requests it is even worse.

I'm not sure I understand the argument about the impact about the footprint. Chucker already leaves a footprint due to the database. Files are temporary and are removed anyway. Manual calls to `delete()` will almost always remove the files. If not, they will be removed after some time due to being in the cache directory. And finally they will be removed after uninstalling the app.

Processing is also theoretically slower but disk IO is nothing compared to the network IO.

Additional benefit of using files (apart from more or less solving OOM issues) is that in the future Chucker could skip storing responses as blobs in the database directly and rely only on file handles.  Not sure if it is a direction that you would like to go, but in my opinion it would be beneficial.

What do you think?

**Comment by vbuberen** [comment]
Ok, I agree with your point. I just didn't think about big payloads properly before and yeah, temp files are the best solution. Also, I should admit that we can always rework the solution at any moment if we ever need it.
So, green light from me. Going to review this PR.

File: library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt [hunk 1]
```diff
@@ -15,6 +19,7 @@ import okhttp3.Response
 import okhttp3.ResponseBody
 import okio.Buffer
 import okio.GzipSource
+import okio.Okio
 
 private const val MAX_BLOB_SIZE = 1000_000L
```
Comment (vbuberen) [inline library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt]: Seems that this const is unused, because the same is present in companion object.

File: library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt [hunk 2]
```diff
@@ -69,10 +83,13 @@ class ChuckerInterceptor @JvmOverloads constructor(
...
 
-        val processedResponse = processResponse(response, transaction)
-        collector.onResponseReceived(transaction)
-
-        return processedResponse
+        processResponseMetadata(response, transaction)
+        return multiCastResponseBody(response) { cachedResponseFile ->
+            val buffer = cachedResponseFile?.let { readResponseBuffer(it, response.isGzipped) }
+            cachedResponseFile?.delete()
+            if (buffer != null) processResponseBody(response, buffer, transaction)
```
Comment (vbuberen) [inline library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt]: This whole block starting with `return` is too hard to read. Let's rewrite it in more simple way without putting multiple functions in `return`.

File: library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt [hunk 3]
```diff
@@ -140,50 +160,62 @@ class ChuckerInterceptor @JvmOverloads constructor(
...
-        val buffer = Buffer().apply { responseSource.use { writeAll(it) } }
+        val teeSource = TeeSource(
+            responseBody.source(),
+            fileFactory.create(),
+            maxContentLength,
+            onResponseBodyReady
+        )
+
+        return response.newBuilder()
+            .body(ResponseBody.create(contentType, contentLength, Okio.buffer(teeSource)))
```
Comment (vbuberen) [inline library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt]: I insist on returning the original `Response` object further in chain without any builders, cloning, etc.
We had enough side effects and issues with providing processed or somehow changed objects. 
And while I see that here we should get the same object I still don't like that it is recreated. 
In some issues we already mentioned that Chucker should be as transparent as possible and this is possible only if we do copy only for Chucker processing without anything like that.

File: library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt [hunk 4]
```diff
@@ -140,50 +160,62 @@ class ChuckerInterceptor @JvmOverloads constructor(
...
             }
         } else {
             transaction.isResponseBodyPlainText = false
 
             val isImageContentType =
                 (contentType?.toString()?.contains(CONTENT_TYPE_IMAGE, ignoreCase = true) == true)
 
-            if (isImageContentType && buffer.size() < MAX_BLOB_SIZE) {
-                transaction.responseImageData = buffer.clone().readByteArray()
+            if (isImageContentType && responseBodyBuffer.size() < MAX_BLOB_SIZE) {
```
Comment (vbuberen) [inline library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt]:
```suggestion
            if (isImageContentType && (responseBodyBuffer.size() < MAX_BLOB_SIZE)) {
```

File: library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt [hunk 5]
```diff
@@ -0,0 +1,77 @@
...
+            throw e
+        }
+
+        if (bytesRead == -1L) {
+            sideStream.close()
+            return -1L
+        }
+
+        totalBytesRead += bytesRead
+        if (!reachedLimit && totalBytesRead <= readBytesLimit) {
```
Comment (vbuberen) [inline library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt]:
```suggestion
        if (!reachedLimit && (totalBytesRead <= readBytesLimit)) {
```

File: library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt [hunk 6]
```diff
@@ -0,0 +1,77 @@
...
+            sink.copyTo(sideStream.buffer(), sink.size() - bytesRead, bytesRead)
```
Comment (vbuberen) [inline library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt]: Why don't you move `sink.size() - bytesRead` into a variable?

File: library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt [hunk 7]
```diff
@@ -0,0 +1,77 @@
...
+    }
+
+    override fun close() {
+        onSideChannelReady(sideChannel)
+        sideStream.close()
+        upstream.close()
+    }
+
+    override fun timeout(): Timeout {
+        return upstream.timeout()
```
Comment (vbuberen) [inline library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt]: What about removing `return`?

File: library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt (hunk 3 above)
Comment (MiSikora) [reply library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt]: I don't see how it would be possible to stream original bytes to two sinks at the same time without replacing the response. This is a mechanism that is used under the hood by `OkHttp` for caching (just a simpler version). It is also recommended way by Square (https://github.com/square/okio/issues/186). Do you have any other approach in mind that would solve the problems addressed by this?

File: library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt (hunk 1 above)
Comment (MiSikora) [reply library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt]: I didn't touch because it is removed in another PR but I'll remove it here after we find a solution to the main issue in this PR. :)

**Comment by MiSikora** [comment]
I will make a CR fixes some time later to focus discussion on things that are not yet clear to me.

> On one side I also realised that the `maxContentLength` constructor parameters was used to truncate ONLY the request and not the response. This PR fixes this.
> I'm still wondering if this approach is a bit over engineered as truncating the responses will probably solve the OOM as well.

I don't think this is really viable. One approach might be to rely on `Content-Length` header but it is not always available and responses can be from bytes to megabytes. We could skip such responses but them we will have some false negatives.

Another approach might to try to do something like this:

```kotlin
val response = chain.proceed(chain.request())
val length = response.body()?.source()?.buffer?.size() ?: return response
if (length <= maxContentLength) {
  // Process response.
}
return response
```

This, however, also does not work. Buffer size is always 0 because it has not been read from at this point and will be some time in the future when the user consumes their network response and process it or whatever they do with it.

The only reason that we can check it right now is because of this piece of code.

https://github.com/ChuckerTeam/chucker/blob/c34300232fab219a7fa4b407243e4b03a3e47634/library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt#L166

And this is the culprit here because it loads the whole response into the memory and potentially leads to OOM.

File: library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt [hunk 8]
```diff
@@ -0,0 +1,79 @@
...
+         */
+        fun onSuccess(file: File)
+
+        /**
+         * Called when there was an issue while copying bytes to the [file].
+         *
+         * It might occur due to an exception thrown while reading bytes or due to exceeding capacity limit.
+         */
+        fun onFailure(exception: IOException, file: File)
+    }
```
Comment (MiSikora) [inline library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt]: I decided to go with a callback instead of magic headers. It gives type safety and is more extensible. In the future it is possible to add `onContentLengthAvailable(length: Long)` method in order to resolve #209.

**Comment by MiSikora** [comment]
I applied most of the suggestions from the CR. One thing still stands - replacing the response. As I mentioned I don't know any other way that would solve the problems addressed by this PR. One thing I'd like to highlight is about the volatile nature of replacing the response and issues that occurred in the past. It is reasonable to be hesitant to do this again, however previous code did not have any tests for `ChuckerInterceptor`. Now that they are being gradually added they should give a confidence in doing such changes.

**Comment by vbuberen** [comment]
Sorry for taking that long. I just want to play around in attempt to not replace response, because I don't know possible approach at the moment. Will try to do tomorrow.

**Comment by MiSikora** [comment]
No worries. Take your time, I just want to provide as much information as possible. I know it is rather big change so it's best to consider it carefully.

**Comment by vbuberen** [comment]
If no other commits planned here, I will merge it.

**Comment by MiSikora** [comment]
Yes, it is ready to go. I'll update #250 soon
